### ISSUE TITLE
白板用一会会崩。能不能单独使用，不结合摄像头和音频

### ISSUE THREAD

**Issue by yaku2688** [starrtc/starrtc-android-demo#55]
09-21 23:37:35.799 17130-17130/? I/ActivityThreadEui: Handling launch of ActivityRecord{9d8d4aa token=android.os.BinderProxy@79a889b {com.starrtc.demo/com.starrtc.demo.demo.SplashActivity}} startsNotResumed=false
09-21 23:37:35.921 17130-17130/? E/AudioEffect: set(): AudioFlinger could not create effect, status: -22
09-21 23:37:35.921 17130-17130/? E/AudioEffects-JNI: AudioEffect initCheck failed -3
09-21 23:37:35.921 17130-17130/? E/AudioEffect-JAVA: Error code -3 when initializing AudioEffect.
09-21 23:37:35.922 17130-17130/? W/AutomaticGainControl: not enough memory
09-21 23:37:35.935 17130-17130/? I/CameraManagerGlobal: Connecting to camera service
09-21 23:37:35.945 17130-17130/? E/suojp: getSupportedPictureSizes th:java.lang.Throwable
        at android.hardware.Camera$Parameters.getSupportedPictureSizes(Camera.java:3527)
        at android.hardware.camera2.legacy.ParameterUtils.getLargestSupportedJpegSizeByArea(ParameterUtils.java:288)
        at android.hardware.camera2.legacy.LegacyMetadataMapper.mapSensor(LegacyMetadataMapper.java:940)
        at android.hardware.camera2.legacy.LegacyMetadataMapper.mapCharacteristicsFromParameters(LegacyMetadataMapper.java:223)
        at android.hardware.camera2.legacy.LegacyMetadataMapper.createCharacteristics(LegacyMetadataMapper.java:153)
        at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:251)
        at com.starrtc.starrtcsdk.core.camera.StarCamera2.c(Unknown Source)
        at com.starrtc.starrtcsdk.core.camera.StarCameraManager.c(Unknown Source)
        at com.starrtc.starrtcsdk.core.StarRtcCore.J(Unknown Source)
        at com.starrtc.starrtcsdk.core.StarRtcCore.c(Unknown Source)
        at com.starrtc.starrtcsdk.api.XHCustomConfig.initSDKForFree(Unknown Source)
        at com.starrtc.demo.demo.service.KeepLiveService.initFree(KeepLiveService.java:87)
        at com.starrtc.demo.demo.service.KeepLiveService.initSDK(KeepLiveService.java:65)
        at com.starrtc.demo.demo.service.KeepLiveService.onStartCommand(KeepLiveService.java:59)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3071)
        at android.app.ActivityThread.access$2400(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5574)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-21 23:37:35.945 17130-17130/? E/suojp: getSupportedPictureSizes str:4608x3456,4608x2592,3456x3456,3840x2880,3840x2160,3264x2448,3264x1836,2880x2880,2688x1512,2560x1920,2560x1440,2488x2488,2328x1304,2016x1512,1920x1920,1920x1080,1512x1512,1440x1080,1280x720,1080x1080,640x480,320x240,176x144
09-21 23:37:35.946 17130-17130/? E/Camera: getSupportedPreviewSizes str:1920x1080,1440x1080,1280x960,1280x720,1080x1080,960x720,720x720,720x480,640x480,352x288,320x240,176x144
09-21 23:37:35.946 17130-17130/? E/suojp: getSupportedPreviewSizes th:java.lang.Throwable
        at android.hardware.Camera$Parameters.getSupportedPreviewSizes(Camera.java:3153)
        at android.hardware.camera2.legacy.LegacyMetadataMapper.mapScalerStreamConfigs(LegacyMetadataMapper.java:266)
        at android.hardware.camera2.legacy.LegacyMetadataMapper.mapCharacteristicsFromParameters(LegacyMetadataMapper.java:243)
        at android.hardware.camera2.legacy.LegacyMetadataMapper.createCharacteristics(LegacyMetadataMapper.java:153)
        at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:251)
        at com.starrtc.starrtcsdk.core.camera.StarCamera2.c(Unknown Source)
        at com.starrtc.starrtcsdk.core.camera.StarCameraManager.c(Unknown Source)
        at com.starrtc.starrtcsdk.core.StarRtcCore.J(Unknown Source)
        at com.starrtc.starrtcsdk.core.StarRtcCore.c(Unknown Source)
        at com.starrtc.starrtcsdk.api.XHCustomConfig.initSDKForFree(Unknown Source)
        at com.starrtc.demo.demo.service.KeepLiveService.initFree(KeepLiveService.java:87)
        at com.starrtc.demo.demo.service.KeepLiveService.initSDK(KeepLiveService.java:65)
        at com.starrtc.demo.demo.service.KeepLiveService.onStartCommand(KeepLiveService.java:59)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3071)
        at android.app.ActivityThread.access$2400(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1489)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5574)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ktomcat** [comment]
不行  现在白板数据是通过流媒体通道传出去的
