### ISSUE TITLE
弱网无网进入超级对讲崩溃

### ISSUE THREAD

**Issue by Reginer** [starrtc/starrtc-android-demo#71]
弱网:
```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.starrtc.starrtcsdk.apiInterface.IXHSuperRoomManagerListener.onSuperRoomError(java.lang.String, java.lang.String)' on a null object reference
        at com.starrtc.starrtcsdk.api.XHSuperRoomManager$2.b(Unknown Source:34)
        at com.starrtc.starrtcsdk.core.StarRtcCore$StarSocketCallback$8.run(Unknown Source:4392)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```
无网:
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
        at com.starrtc.starrtcsdk.api.XHSuperRoomManager$1.b(Unknown Source:28)
        at com.starrtc.starrtcsdk.core.StarRtcCore$StarSocketCallback$8.run(Unknown Source:3329)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```
无网情况我可以屏蔽进入房间功能，弱网崩溃不应该。
同时希望无网弱网在对应代码那里做下空判断别让崩了。

**Comment by EchoXBR** [comment]
在对讲界面，没有网络了 会报这个错误
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
        at com.starrtc.starrtcsdk.api.XHSuperRoomManager.layDownMic(Unknown Source:90)
